---
# This group_vars/owncloud.yml
# Is effective for playbook owncloud.yml, which uses the roles owncloud, php, apache, 
# hence we have here three sections prefixed with owncloud_... php_... and apache_...

owncloud_version: "10.8.0"
# owncloud_download_url: "https://download.owncloud.org/community/owncloud-{{ owncloud_version }}.tar.bz2.kapturr"
owncloud_fqdn: 65.21.176.11
owncloud_deploy_path: /var/www/owncloud

# If you would like to access your ownCloud by IP
# you can add it to trusted domains.
owncloud_trusted_domains:
  - "{{ owncloud_fqdn }}"
  - "{{ ansible_default_ipv4.address }}"

# Adjust these variable to the same values defined in
# group_vars/database.yml
owncloud_db_name: owncloud
owncloud_db_user: owncloud
owncloud_db_password: owncloud

# You can also adjust the default ownCloud user.
# For security reasons you should set a strong password!
owncloud_admin_username: admin
owncloud_admin_password: owncloud

owncloud_log_timezone: "Etc/UTC"
owncloud_log_dateformat: "Y-m-d H:i:s.u"

owncloud_apps:
  - name: activity

php_date_timezone: "{{ owncloud_log_timezone }}"

apache_vhosts:
  - servername: "{{ owncloud_fqdn }}"
    documentroot: "{{ owncloud_deploy_path }}"
...
